apiVersion: v1
kind: Service
metadata:
  namespace: car-dealer
  name: car-dealer-service
spec:
  type: LoadBalancer
  selector:
    app: car-dealer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000

